exports.content = {
    cancel : "لغو کردن",
    error404 : "404! we can't find this page",
    readmore : "Read more &raquo;",
    top_list : "پست های اول",
    
    pagetitle_homepage : "خانه",
    pagetitle_aboutme : "درباره",
    pagetitle_updatepost : "ویرایش پست",
    pagetitle_trash : "سطل زباله ی پست ها",
    pagetitle_password : "تغییر رمز",
    pagetitle_404 : "Error 404",

    nav_blog : "صفحه ی اصلی",
    nav_aboutme: "درباره ی سامانه",
    nav_admin_login: "ورود استاد",
    nav_admin: "ادمین",
    nav_admin_setting: "تنظیمات",
    nav_admin_data : "Data Center",
    nav_admin_addpost: "افزودن پست",
    nav_admin_myposts: "پست ها",
    nav_admin_password: "رمز ورود",
    nav_admin_logout: "خروج از حساب",

    page_older : "پست های قدیمی →",
    page_newer : "← پست های جدید",

    relevant_tags: "تگ ها",
    relevant_links: "لینک ها",
    relevant_meweb: "تارنما",

    login_username: "نام کاربری",
    login_password: "رمز‌ ورود",
    login_submit: "ورود به حساب",
    login_failed: "نام کاربری یا رمز ورود نادرست است!",

    tip_nopost: "آفرین.. بیا اولین پستت رو بذار ",
    tip_noaboutme: "در اینجا متن درباره ی من قرار میگیرد",

    setting_lang: "زبان",
    setting_lang_tip: "",
    setting_sitename: "اسم سامانه",
    setting_sitename_tip: "",
    setting_sitedesc: "توضیحات سامانه",
    setting_sitedesc_tip: "",
    setting_keywords: "کلمات کلیدی",
    setting_keywords_tip: "",
    setting_commentservice: "سرویس کامنت آنلاین",
    setting_commentservice_tip: "سامانه ی ما از سرویس های کامنت <a href='http://disqus.com' target='_blank'>Disqus</a>, <a href='http://www.livefyre.com/' target='_blank'>Lifeflye</a> and <a href='http://duoshuo.com/' target='_blank'>duoshuo</a> پشتیبانی میکند",
    setting_commentserviceid: "آی دی سرویس کامنت",
    setting_commentserviceid_tip: "",
    setting_gaid: "آی دی ترکینگ گوگل",
    setting_gaid_tip: "",
    setting_sitelogo: "لوگوی سامانه",
    setting_sitelogo_tip: "",
    setting_theme: "تم سامانه",
    setting_theme_tip: "",
    setting_footer: "پاورقی",
    setting_footer_tip: "",
    setting_aboutme: "در باره ی ما",
    setting_aboutme_tip: "",
    setting_links: "پیوند ها",
    setting_links_tip: "یک پیوند  به سامانه یا  تارنمایی دیگر",
    setting_meweb: "من و تارنما",
    setting_meweb_tip: "",
    setting_host_local: "فایل های محلی",
    setting_hljs_host: "Highlight.js host",
    setting_hljs_host_tip: "",
    setting_hljs_theme: "Highlight.js theme",
    setting_hljs_theme_tip: "",
    setting_hljs_theme_demo: "Live demo",
    setting_jquery_host: "jQuery lib host",
    setting_jquery_host_tip: "",
    setting_submit: "ثبت",
   
    post_title: "عنوان",
    post_tags: "تگ ها",
    post_tags_tip: "تگ ها با فاصله یا سمی کالن جدا میشوند",
    post_content: "متن پست",
    post_content_tip: "",
    post_created: "تاریخ پست",
    post_created_tip: "برای ثبت تاریخ این قسمت را خالی بگذارید",
    post_created_tip_update: "",
    post_submit: "ثبت",

    mypost_admin: "Post Admin",
    mypost_trash: "Trash List",
    mypost_th_id: "ID",
    mypost_th_title: "عنوان",
    mypost_th_created: "تاریخ ایجاد",
    mypost_th_actions: "اعمال",
    mypost_action_update: "ویرایش",
    mypost_action_trash: "فرستادن به سطل زباله",
    mypost_action_remove: "پاک کردن",
    mypost_action_restore: "بازیابی کردن",
    mypost_trash_empty: "هیچ پستی در سطل زباله نیست",
    mypost_trash_tip: "آیا از انتقال این پست به سطل زباله مطمئن هستید؟",
    mypost_remove_tip: "آیا از پاک کردن این پست برای همیشه مطمئن هستید؟",
    mypost_adminlink: "ادمین",
    mypost_trashlink: "سطل زباله",
    mypost_addtop: "افزودن بالا",
    mypost_deltop: "پاک کردن پایین",

    password_username: "نام کاربری",
    password_oldpassword: "پسورد قبلی",
    password_newpassword: "پسورد جدید",
    password_confirmpassword: "پسورد جدید را بار دیگر وارد کنید",
    password_submit: "ثبت",
    password_failed_username: "Username is not wellformated",
    password_failed_oldpassword: "پسورد قبلی را نادرست وارد کردید",
    password_failed_newpassword: "پسورد جدید به درستی وارد نشده و باید 6 کارکتر باشد",
    password_failed_match: "پسورد جدید با تکرارش مطابقت ندارد",
    password_changed: "پسورد تغییر کرد",

    admindata_title : "پشتیبان گیری و بازیابی",
    admindata_backup : "پشتیبان گیری",
    admindata_backup_tip : "با فشردن دکمه ی زیر پست ها و تنظیمات سامانه ذخیره میشوند",
    admindata_restore : "بازیابی",
    admindata_restore_upload : "لطفا فایل پشتیبان به فرمت زیپ را انتخاب کنید",
    admindata_restorefilenotfound : "فایل زیپ یافت نشد",
    admindata_restore_file : "فایل داده ی مورد بازیابی",
    admindata_restore_tip : "با بازیابی تمام اطلاعات شما تغییر خواهد کرد .. مواظب باشید",
    admindata_dorestore : "در حال بازیابی",
    admindata_restore_succ : "بازیابی موفقیت آمیز بود"
};
